erp.jdbc.url=jdbc:mysql://localhost:3306/erp_db
erp.jdbc.user=jazl
erp.jdbc.pass=jazl4zayn

auth.jdbc.url=jdbc:mysql://localhost:3306/auth_db
auth.jdbc.user=jazl
auth.jdbc.pass=jazl4zayn

drop_deadline=2025-12-31

# add your username and password as required, replace the existing one